// Mocks generated by Mockito 5.4.6 from annotations
// in weather_app/test/feature/weather/mocks/mock_dependencies.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:get/get.dart' as _i3;
import 'package:http/http.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:shared_preferences/shared_preferences.dart' as _i2;
import 'package:weather_app/api/api_client.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSharedPreferences_0 extends _i1.SmartFake
    implements _i2.SharedPreferences {
  _FakeSharedPreferences_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInternalFinalCallback_1<T> extends _i1.SmartFake
    implements _i3.InternalFinalCallback<T> {
  _FakeInternalFinalCallback_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_2<T> extends _i1.SmartFake implements _i3.Response<T> {
  _FakeResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i4.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get appBaseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#appBaseUrl),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#appBaseUrl),
            ),
          )
          as String);

  @override
  _i2.SharedPreferences get sharedPreferences =>
      (super.noSuchMethod(
            Invocation.getter(#sharedPreferences),
            returnValue: _FakeSharedPreferences_0(
              this,
              Invocation.getter(#sharedPreferences),
            ),
          )
          as _i2.SharedPreferences);

  @override
  int get timeoutInSeconds =>
      (super.noSuchMethod(Invocation.getter(#timeoutInSeconds), returnValue: 0)
          as int);

  @override
  set token(String? _token) => super.noSuchMethod(
    Invocation.setter(#token, _token),
    returnValueForMissingStub: null,
  );

  @override
  _i3.InternalFinalCallback<void> get onStart =>
      (super.noSuchMethod(
            Invocation.getter(#onStart),
            returnValue: _FakeInternalFinalCallback_1<void>(
              this,
              Invocation.getter(#onStart),
            ),
          )
          as _i3.InternalFinalCallback<void>);

  @override
  _i3.InternalFinalCallback<void> get onDelete =>
      (super.noSuchMethod(
            Invocation.getter(#onDelete),
            returnValue: _FakeInternalFinalCallback_1<void>(
              this,
              Invocation.getter(#onDelete),
            ),
          )
          as _i3.InternalFinalCallback<void>);

  @override
  bool get initialized =>
      (super.noSuchMethod(Invocation.getter(#initialized), returnValue: false)
          as bool);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  Map<String, String> updateHeader(String? token, {bool? setHeader = true}) =>
      (super.noSuchMethod(
            Invocation.method(#updateHeader, [token], {#setHeader: setHeader}),
            returnValue: <String, String>{},
          )
          as Map<String, String>);

  @override
  Map<String, String> getHeader() =>
      (super.noSuchMethod(
            Invocation.method(#getHeader, []),
            returnValue: <String, String>{},
          )
          as Map<String, String>);

  @override
  _i6.Future<_i3.Response<dynamic>> getData(
    String? uri, {
    Map<String, dynamic>? query,
    Map<String, String>? headers,
    bool? handleError = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getData,
              [uri],
              {#query: query, #headers: headers, #handleError: handleError},
            ),
            returnValue: _i6.Future<_i3.Response<dynamic>>.value(
              _FakeResponse_2<dynamic>(
                this,
                Invocation.method(
                  #getData,
                  [uri],
                  {#query: query, #headers: headers, #handleError: handleError},
                ),
              ),
            ),
          )
          as _i6.Future<_i3.Response<dynamic>>);

  @override
  _i6.Future<_i3.Response<dynamic>> postData(
    String? uri,
    dynamic body, {
    Map<String, String>? headers,
    int? timeout,
    bool? handleError = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #postData,
              [uri, body],
              {#headers: headers, #timeout: timeout, #handleError: handleError},
            ),
            returnValue: _i6.Future<_i3.Response<dynamic>>.value(
              _FakeResponse_2<dynamic>(
                this,
                Invocation.method(
                  #postData,
                  [uri, body],
                  {
                    #headers: headers,
                    #timeout: timeout,
                    #handleError: handleError,
                  },
                ),
              ),
            ),
          )
          as _i6.Future<_i3.Response<dynamic>>);

  @override
  _i6.Future<_i3.Response<dynamic>> pstOtp(
    String? uri,
    dynamic body, {
    Map<String, String>? headers,
    int? timeout,
    bool? handleError = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #pstOtp,
              [uri, body],
              {#headers: headers, #timeout: timeout, #handleError: handleError},
            ),
            returnValue: _i6.Future<_i3.Response<dynamic>>.value(
              _FakeResponse_2<dynamic>(
                this,
                Invocation.method(
                  #pstOtp,
                  [uri, body],
                  {
                    #headers: headers,
                    #timeout: timeout,
                    #handleError: handleError,
                  },
                ),
              ),
            ),
          )
          as _i6.Future<_i3.Response<dynamic>>);

  @override
  _i6.Future<_i3.Response<dynamic>> postMultipartData(
    String? uri,
    Map<String, String>? body,
    List<_i4.MultipartBody>? multipartBody, {
    Map<String, String>? headers,
    bool? handleError = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #postMultipartData,
              [uri, body, multipartBody],
              {#headers: headers, #handleError: handleError},
            ),
            returnValue: _i6.Future<_i3.Response<dynamic>>.value(
              _FakeResponse_2<dynamic>(
                this,
                Invocation.method(
                  #postMultipartData,
                  [uri, body, multipartBody],
                  {#headers: headers, #handleError: handleError},
                ),
              ),
            ),
          )
          as _i6.Future<_i3.Response<dynamic>>);

  @override
  _i6.Future<_i3.Response<dynamic>> putData(
    String? uri,
    dynamic body, {
    Map<String, String>? headers,
    bool? handleError = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #putData,
              [uri, body],
              {#headers: headers, #handleError: handleError},
            ),
            returnValue: _i6.Future<_i3.Response<dynamic>>.value(
              _FakeResponse_2<dynamic>(
                this,
                Invocation.method(
                  #putData,
                  [uri, body],
                  {#headers: headers, #handleError: handleError},
                ),
              ),
            ),
          )
          as _i6.Future<_i3.Response<dynamic>>);

  @override
  _i6.Future<_i3.Response<dynamic>> deleteData(
    String? uri, {
    Map<String, String>? headers,
    bool? handleError = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #deleteData,
              [uri],
              {#headers: headers, #handleError: handleError},
            ),
            returnValue: _i6.Future<_i3.Response<dynamic>>.value(
              _FakeResponse_2<dynamic>(
                this,
                Invocation.method(
                  #deleteData,
                  [uri],
                  {#headers: headers, #handleError: handleError},
                ),
              ),
            ),
          )
          as _i6.Future<_i3.Response<dynamic>>);

  @override
  _i3.Response<dynamic> handleResponse(
    _i7.Response? response,
    String? uri,
    bool? handleError,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#handleResponse, [response, uri, handleError]),
            returnValue: _FakeResponse_2<dynamic>(
              this,
              Invocation.method(#handleResponse, [response, uri, handleError]),
            ),
          )
          as _i3.Response<dynamic>);

  @override
  void onInit() => super.noSuchMethod(
    Invocation.method(#onInit, []),
    returnValueForMissingStub: null,
  );

  @override
  void onReady() => super.noSuchMethod(
    Invocation.method(#onReady, []),
    returnValueForMissingStub: null,
  );

  @override
  void onClose() => super.noSuchMethod(
    Invocation.method(#onClose, []),
    returnValueForMissingStub: null,
  );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
    Invocation.method(#$configureLifeCycle, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [SharedPreferences].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPreferences extends _i1.Mock implements _i2.SharedPreferences {
  MockSharedPreferences() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Set<String> getKeys() =>
      (super.noSuchMethod(
            Invocation.method(#getKeys, []),
            returnValue: <String>{},
          )
          as Set<String>);

  @override
  Object? get(String? key) =>
      (super.noSuchMethod(Invocation.method(#get, [key])) as Object?);

  @override
  bool? getBool(String? key) =>
      (super.noSuchMethod(Invocation.method(#getBool, [key])) as bool?);

  @override
  int? getInt(String? key) =>
      (super.noSuchMethod(Invocation.method(#getInt, [key])) as int?);

  @override
  double? getDouble(String? key) =>
      (super.noSuchMethod(Invocation.method(#getDouble, [key])) as double?);

  @override
  String? getString(String? key) =>
      (super.noSuchMethod(Invocation.method(#getString, [key])) as String?);

  @override
  bool containsKey(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#containsKey, [key]),
            returnValue: false,
          )
          as bool);

  @override
  List<String>? getStringList(String? key) =>
      (super.noSuchMethod(Invocation.method(#getStringList, [key]))
          as List<String>?);

  @override
  _i6.Future<bool> setBool(String? key, bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setBool, [key, value]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> setInt(String? key, int? value) =>
      (super.noSuchMethod(
            Invocation.method(#setInt, [key, value]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> setDouble(String? key, double? value) =>
      (super.noSuchMethod(
            Invocation.method(#setDouble, [key, value]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> setString(String? key, String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setString, [key, value]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> setStringList(String? key, List<String>? value) =>
      (super.noSuchMethod(
            Invocation.method(#setStringList, [key, value]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> remove(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#remove, [key]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> commit() =>
      (super.noSuchMethod(
            Invocation.method(#commit, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<void> reload() =>
      (super.noSuchMethod(
            Invocation.method(#reload, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}
